apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
spec:
  selector:
    matchLabels:
      app: authorization
  replicas: 1
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
        - name: authorization
          image: basime/lms_authentication:latest
          ports:
          - containerPort: 5099
