apiVersion: v1
kind: Service
metadata:
  name: authorization-serv
spec:
  type: NodePort
  selector:
    app: authorization
  ports:
  - name: authorization
    port: 5099
    protocol: TCP
    targetPort: 5099
